"""
Django settings for lineoa_official project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""


import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p8y(vc)bm8rh%u2vewvw8mcf_9aye_6nsfb=0e#*49n(q9t4)%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_bootstrap5',
    'corsheaders',
    'linedtb',
    'line_detailpayment',
    # 'line_reciept_pdf',
    'line_pdf',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]
CORS_ORIGIN_ALLOW_ALL = True

ROOT_URLCONF = 'lineoa_official.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lineoa_official.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'NCAP_20230923',
        'USER': 'sa',
        'PASSWORD': 'Server*1',
        'HOST': '103.253.75.218\\mssqlserverv2012',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
}
FR_SERVER = {
        'PROTOCOL': 'http',
        'HOST': 'localhost',
        'PORT': '8099',
}

# {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# MEDIA_URL = 'images/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


FASTREPORT_API_URL = "https://api.fastreport.com/api/report"  # URL ของ FastReport Server หรือ Cloud API

FASTREPORT_API_TOKEN = "your_api_token"

FASTREPORT_REPORT_ID = "LINEOA_test"

  # Report Server


# adobe

# ADOBE_CREDENTIALS_PATH = os.path.join(BASE_DIR, "adobe_credentials", "credentials.json")

# ADOBE_API_KEY = os.getenv("ADOBE_API_KEY", "d2faabfac1744b3598c3c0824b7a8338")

# if os.path.exists(ADOBE_CREDENTIALS_PATH):
#     with open(ADOBE_CREDENTIALS_PATH, "r", encoding="utf-8") as f:
#         ADOBE_CREDENTIALS = json.load(f)

#     # ✅ ดึงค่า Client ID และ Secret
#     ADOBE_CLIENT_ID = ADOBE_CREDENTIALS.get("CLIENT_ID")
#     ADOBE_CLIENT_SECRET = ADOBE_CREDENTIALS.get("CLIENT_SECRETS")[0]  # ดึงค่าแรกจาก Array
#     ADOBE_ORG_ID = ADOBE_CREDENTIALS.get("ORG_ID")
#     ADOBE_SCOPES = " ".join(ADOBE_CREDENTIALS.get("SCOPES", []))  # รวม Scope เป็น String
# else:
#     ADOBE_CLIENT_ID = None
#     ADOBE_CLIENT_SECRET = None
#     ADOBE_ORG_ID = None
#     ADOBE_SCOPES = None